version: "3.9"
services:
  web:
    build: services/frontend
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
  reader:
    build: services/reader
    ports:
      - "8080:8080"
    networks:
      - frontend
      - cache
  writer:
    build: services/writer
    ports:
      - "8081:8081"
    networks:
      - backend
      - cache
  redis:
    image: "redis:alpine"
    networks:
      - cache

networks:
  frontend:
  backend:
  cache:
